### PR TITLE
385 change state to region throughout the extension

### PR DESCRIPTION
**Pull request by jjeancharles**

### CODE REVIEW

**Comment by jjeancharles** [comment]
Package.json may cause problems when merging, not too sure

**Comment by SebastianZimmeck** [comment]
> Package.json may cause problems when merging, not too sure

The dependencies there will just be automatically updated, right? This should not cause any problems. Or are there any other reasons why you suspect this merge may cause problems?

**Comment by jjeancharles** [comment]
When first running main it said Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db, and I just want to confirm it was ok that I updated it. I wasn't sure when I first joined if this wasn't updated for a reason

**Comment by jjeancharles** [comment]
> > Package.json may cause problems when merging, not too sure
> 
> The dependencies there will just be automatically updated, right? This should not cause any problems. Or are there any other reasons why you suspect this merge may cause problems?

When first running main it said Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db, and I just want to confirm it was ok that I updated it. I wasn't sure when I first joined if this wasn't updated for a reason

**Comment by SebastianZimmeck** [comment]
>  I just want to confirm it was ok that I updated it

Sounds good! I think it is OK. This may be just a local setup issue. But @danielgoldelman can confirm.

**Pull request closed without merging**
