### PR TITLE
Issue 490 - Show Current Browsing Session Evidence

### LINKED ISSUE #490: Only show evidence of current browsing session
When you visit a website we only want to show evidence in the popup that relates to the current website visit, not past visits.

### PR DESCRIPTION
**Pull request by jjeancharles**
Closes #490

### CODE REVIEW

**Comment by lr-brown** [comment]
Will review after discussed changes have been made

**Comment by lr-brown** [comment]
> > Will review after discussed changes have been made
> 
> @danielgoldelman, can you make the outstanding changes?

The changes were discussed with @jjeancharles if he is unable to do it I can do it!

**Comment by SebastianZimmeck** [comment]
OK, @jjeancharles, please go ahead then, or let @lr-brown know if you do not have time.

**Comment by jjeancharles** [comment]
The changes that were discussed have now been committed, this PR is ready to be reviewed. @SebastianZimmeck & @lr-brown

**Review by lr-brown — APPROVED** [review]

**Pull request merged**
