### PR TITLE
Fix watchlist problems

### PR DESCRIPTION
**Pull request by danielgoldelman**

### CODE REVIEW

**Comment by danielgoldelman** [comment]
pr held until new changes to 512 have been implemented

**Review by SebastianZimmeck — CHANGES_REQUESTED** [review]
Thanks, @danielgoldelman, it works. But also please change the readme accordingly.

I'd say delete your earlier readme change and instead say:
- When storing a Watchlist General Keyword, a user would be alerted the first time a keyword is entered or shared by a site
- For all other keyword categories, a user would be alerted every time the keyword is collected or shared

(assuming that is how it is and that this is the terminology from the UI; in any case please describe in a few sentences how the Watchlist works using the terms from the UI)

**Comment by SebastianZimmeck** [comment]
We first need to resolve the [open points](https://github.com/privacy-tech-lab/privacy-pioneer/issues/512#issuecomment-1625737299) before we can merge here.

**Review by jjeancharles — COMMENTED** [review]
Reviewed the changes and everything that was fixed is working as intended!

**Comment by SebastianZimmeck** [comment]
OK, I am currently on the train, which is not ideal for testing this functionality. I wlll try in 11 hours or so with a more stable Internet connection.

**Review by SebastianZimmeck — APPROVED** [review]
OK, I checked the General Keywords. The other ones I will check in more detail. We can start with the usability study.

**Pull request merged**
